### ISSUE TITLE
男角色放大招时，翅膀脱离后背了，女角色的尾巴却是正常的！

### ISSUE THREAD

**Issue by cloudhu** [liuhaopen/UnityMMO#10]
额，还有地面穿透问题。对于ECS，Sky net，Lua框架好多地方我还没有搞懂，希望大佬多多指教。

**Comment by liuhaopen** [comment]
男主翅膀脱离后背是因为没设置好挂点，这个是在该技能的 timeline 文件可以弄的，一般这个是美术慢慢调整的，我是比较懒随便拉了下，等下我调好它吧，你不说我还真没留意到。
我想项目初期阶段的话还是优先把大部分功能做出来，一些细节上的东西后面可以慢慢优化。ECS 的资料网上也有不少的，我的 csdn 里也写了几篇 unity ecs 框架的源码解析，有空可以看看。skynet 的话我也是第一次用，lua 的话源码只有两万多行也建议你看看，源码解析方面的文章也很多了。

**Comment by cloudhu** [comment]
哈哈，太感谢了，我去找找CSDN上的解析，是同一个ID吗?我也在研究官方案例来着！

**Comment by liuhaopen** [comment]
男主翅膀的提交了，pull 下 Resource 项目就可以了

**Comment by cloudhu** [comment]
好的，非常感谢，我要好好向您学习一下！

**Comment by liuhaopen** [comment]
Timeline 里特效的挂点我是在 TimelineModule.cs 里，根据轨道名 “ParticleTrack_挂点名” 设置的，比如男主的翅膀要挂到 wing 子节点，那该特效轨道就命名为 ParticleTrack_wing，暂时还不知道有没其它方式可以指定挂点，有更好方法的话也告诉我一下哈

**Comment by cloudhu** [comment]
谢谢大佬指教，我还不会Timeline，抽空学习一下！
