### ISSUE TITLE
大佬,可以帮忙看下错误吗

### ISSUE THREAD

**Issue by ggyongfu** [liuhaopen/UnityMMO#12]
[:01000017] lua call [1000016 to :1000017 : 14 msgsz = 25] error : /root/u3d/skynet/lualib/skynet.lua:617: /root/u3d/skynet/lualib/skynet.lua:184: /root/u3d/lualib/Common/Util/sprotoloader.lua:21: nil sproto at index 1
stack traceback:
 [C]: in function 'sproto.core.loadproto'
 /root/u3d/lualib/Common/Util/sprotoloader.lua:21: in function 'Common.Util.sprotoloader.load'
 /root/u3d/service/msgagent.lua:60: in local 'f'
 /root/u3d/service/msgagent.lua:92: in upvalue 'f'
 /root/u3d/skynet/lualib/skynet.lua:141: in function </root/u3d/skynet/lualib/skynet.lua:113>
stack traceback:
 [C]: in function 'assert'
 /root/u3d/skynet/lualib/skynet.lua:617: in function 'skynet.dispatch_message'
[:01000016] lua call [1000017 to :1000016 : 14 msgsz = 0] error : /root/u3d/skynet/lualib/skynet.lua:617: /root/u3d/skynet/lualib/skynet.lua:184: /root/u3d/skynet/lualib/skynet.lua:359: call failed
stack traceback:
 [C]: in function 'error'
 /root/u3d/skynet/lualib/skynet.lua:359: in upvalue 'yield_call'
 /root/u3d/skynet/lualib/skynet.lua:376: in function 'skynet.call'
 /root/u3d/service/gated.lua:42: in function </root/u3d/service/gated.lua:18>
 (...tail calls...)
 /root/u3d/skynet/lualib/snax/gateserver.lua:151: in upvalue 'f'
 /root/u3d/skynet/lualib/skynet.lua:141: in function </root/u3d/skynet/lualib/skynet.lua:113>
stack traceback:
 [C]: in function 'assert'
 /root/u3d/skynet/lualib/skynet.lua:617: in function 'skynet.dispatch_message'
[:0100000d] invalid client (fd = 11) error = /root/u3d/skynet/lualib/snax/loginserver.lua:146: /root/u3d/skynet/lualib/skynet.lua:359: call failed

我在服务器部署了,但是客户端连接的时候提示这个错误.
我看到UnityMMOAccount库有数据写入

**Comment by liuhaopen** [comment]
读取不了协议文件，应该是需要把 UnityMMO/Lua/Common, Config, Proto 这三个文件夹也复制到你的服务端 Server 的同级目录去，那些是双端共用的文件，需要手动复制过去，以后有空再写个脚本处理吧

**Comment by ggyongfu** [comment]
> 读取不了协议文件，应该是需要把 UnityMMO/Lua/Common, Config, Proto 这三个文件夹也复制到你的服务端 Server 的同级目录去，那些是双端共用的文件，需要手动复制过去，以后有空再写个脚本处理吧

大佬,好像我复制了进去好像也是报同意的错误

**Comment by ggyongfu** [comment]
> 读取不了协议文件，应该是需要把 UnityMMO/Lua/Common, Config, Proto 这三个文件夹也复制到你的服务端 Server 的同级目录去，那些是双端共用的文件，需要手动复制过去，以后有空再写个脚本处理吧

可以了,大佬 ..看漏同级目录..谢谢你
