### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cloudfreexiao** [liuhaopen/UnityMMO#13]
环境 mac unity 2019.3
运行错误日志
`xLua exception : luaopen_client_crypt
   at (wrapper managed-to-native) XLua.LuaDLL.Lua.luaopen_client_crypt(intptr`

`xLua exception : luaopen_sproto_core
   at (wrapper managed-to-native) XLua.LuaDLL.Lua.luaopen_sproto_core(intptr)`

mac 相关的 lua 库 资源 有问题嘛？

另外 server 端 缺少文件
`service/main.lua:2: module 'Common.Util.util' not fou`

**Comment by liuhaopen** [comment]
不好意思，我还没处理过 ios 平台的，你需要跑下 UnityMMO/Build/make_ios_lua53.sh 脚本生成对应的
 xlua 库，因为我在 xlua 的基础上加了 sproto 和 lua-crypt 等第三方库，是需要重新编译的。
详情可见 ： [XLua增加删除第三方lua库](https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E5%A2%9E%E5%8A%A0%E5%88%A0%E9%99%A4%E7%AC%AC%E4%B8%89%E6%96%B9lua%E5%BA%93.md)

**Comment by cloudfreexiao** [comment]
编译通过了  服务端 缺少 文件 麻烦 提交下 D)
另外 服务端 考虑 另建个仓库 单独 处理嘛 合在一起感觉 挺 麻烦的

**Comment by liuhaopen** [comment]
服务端缺少什么文件？我看之前有几个提 issue 的都能搭建好的。
服务端是有考虑另建仓库的，不过前期开发经常会同时修改到前后端的东西，现在前端的代码和资源已经分仓库了，每次改东西后要两个地方检查提交，再分多个后端的话我以后提交就更麻烦了。
最起码要等我重新整理双端的代码风格后再分仓库了

**Comment by cloudfreexiao** [comment]
具体信息如下 刚才的 issue 我写的不详细
`[:01000009] lua loader error : /root/workspace/MMOServer/service/main.lua:2: module 'Common.Util.util' not found:
	no field package.preload['Common.Util.util']
	no file '/root/workspace/MMOServer/lualib/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/lualib/Common/Util/util/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/skynet/lualib/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/skynet/lualib/Common/Util/util/init.lua'
	no file '/root/workspace/MMOServer/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/game/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/../Lua/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/game/scene/system/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/../Lua/Common/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/lualib/ECS/Common/Util/util.lua'
	no file '/root/workspace/MMOServer/skynet/luaclib/Common/Util/util.so'
	no file '/root/workspace/MMOServer/lualib/ECS/Common/Util/util.so'
	no file '/root/workspace/MMOServer/skynet/luaclib/Common.so'
	no file '/root/workspace/MMOServer/lualib/ECS/Common.so'
stack traceback:
	[C]: in function 'require'
	/root/workspace/MMOServer/service/main.lua:2: in local 'main'
	/root/workspace/MMOServer/skynet/lualib/loader.lua:48: in main chunk
[:01000009] KILL self
[:01000002] KILL self`

**Comment by liuhaopen** [comment]
把 UnityMMO/Lua 里的 Config,Proto,Common 三个目录也复制过去并保持目录层级关系
这三个目录是双端共用的，ReadMe 的 Usage 有写，不过确实坑过好多人，但我又不想搞双份同样的代码

**Comment by cloudfreexiao** [comment]
好的 谢谢
