### ISSUE TITLE
Why doesn't it work?

### ISSUE THREAD

**Issue by Chaleeshadow** [liuhaopen/UnityMMO#17]
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 192.168.1.36:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 192.168.1.36:2013
[:01000004] connect from 192.168.1.36:54473 4
[:01000006] LAUNCH harbor 1 16777221
[:01000004] Harbor 1 (fd=4) report 192.168.1.36:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:01000009] Server start
[:0100000a] LAUNCH snlua protoloader
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000c] Start debug console at 127.0.0.1:8000
[:0100000d] LAUNCH snlua logind
[:0100000e] LAUNCH snlua logind
[:0100000f] LAUNCH snlua logind
[:01000010] LAUNCH snlua logind
[:01000011] LAUNCH snlua logind
[:01000012] LAUNCH snlua logind
[:01000013] LAUNCH snlua logind
[:01000014] LAUNCH snlua logind
[:01000015] LAUNCH snlua logind
[:0100000d] login server listen at : 0.0.0.0 8001
[:01000016] LAUNCH snlua gated 16777229 1 1
[:01000016] Listen on 0.0.0.0:8888
[:01000017] LAUNCH snlua msgagent
[:01000018] LAUNCH snlua msgagent
[:01000019] LAUNCH snlua msgagent
[:0100001a] LAUNCH snlua msgagent
[:0100001b] LAUNCH snlua msgagent
[:0100001c] LAUNCH snlua msgagent
[:0100001d] LAUNCH snlua msgagent
[:0100001e] LAUNCH snlua msgagent
[:0100001f] LAUNCH snlua msgagent
[:01000020] LAUNCH snlua msgagent
[:01000021] LAUNCH snlua world
[:01000022] LAUNCH snlua scene 16777249
[:01000023] LAUNCH snlua scene 16777249
[:01000024] LAUNCH snlua chat
[:01000025] LAUNCH snlua dbserver
[:01000026] LAUNCH snlua dbserver
[:01000027] LAUNCH snlua id_service
[:01000009] KILL self
[:01000002] KILL self

**Comment by liuhaopen** [comment]
confirm if your host can ping the server, type the correct ip and port in login view

**Comment by Chaleeshadow** [comment]
Which launcher is fileserver? 
Thanks.

**Comment by liuhaopen** [comment]
no file server required on the pc side, it is use for update res in android or iOS
