### ISSUE TITLE
Build Bundle Resources Error 

### ISSUE THREAD

**Issue by Chaleeshadow** [liuhaopen/UnityMMO#25]
![Untitled](https://user-images.githubusercontent.com/40860287/85951197-cbdbe500-b98b-11ea-9178-d431609ca919.jpg)
How to Fix this error, Can you suggest me please

**Comment by liuhaopen** [comment]
Which platform you just built, I have no problem testing locally：
![image](https://user-images.githubusercontent.com/11566473/85965609-c1ebcd80-b9ef-11ea-8a4f-9dcdc735a533.png)
I have no problem testing locally?

**Comment by Chaleeshadow** [comment]
Ok I did build it 
but i can't run game launcher 
![Untitled](https://user-images.githubusercontent.com/40860287/86004918-29306e80-ba3e-11ea-9ec0-7e69414c5e2c.jpg)
`FileNotFoundException: D:/UnityMMO/bin/UnityMMO_Data/StreamingAssets/files.txt does not exist`
What did I do wrong?

**Comment by liuhaopen** [comment]
I think your build failed, why don't you run on unity editor?
I rarely build pc clients.
