### ISSUE TITLE
Table 'UnityMMOGame.RoleList' doesn't exist

### ISSUE THREAD

**Issue by xzzwandi** [liuhaopen/UnityMMO#27]
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000004] connect from 127.0.0.1:48326 4
[:01000006] LAUNCH harbor 1 16777221
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:01000009] Server start
[:0100000a] LAUNCH snlua protoloader
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000c] Start debug console at 127.0.0.1:8000
[:0100000d] LAUNCH snlua logind
[:0100000e] LAUNCH snlua logind
[:0100000f] LAUNCH snlua logind
[:01000010] LAUNCH snlua logind
[:01000011] LAUNCH snlua logind
[:01000012] LAUNCH snlua logind
[:01000013] LAUNCH snlua logind
[:01000014] LAUNCH snlua logind
[:01000015] LAUNCH snlua logind
[:0100000d] login server listen at : 0.0.0.0 8001
[:01000016] LAUNCH snlua gated 16777229 1 1
[:01000016] Listen on 0.0.0.0:8888
[:01000017] LAUNCH snlua msgagent
[:01000018] LAUNCH snlua msgagent
[:01000019] LAUNCH snlua msgagent
[:0100001a] LAUNCH snlua msgagent
[:0100001b] LAUNCH snlua msgagent
[:0100001c] LAUNCH snlua msgagent
[:0100001d] LAUNCH snlua msgagent
[:0100001e] LAUNCH snlua msgagent
[:0100001f] LAUNCH snlua msgagent
[:01000020] LAUNCH snlua msgagent
[:01000021] LAUNCH snlua world
[:01000022] LAUNCH snlua scene 16777249
[:01000023] LAUNCH snlua scene 16777249
[:01000024] LAUNCH snlua chat
[:01000025] LAUNCH snlua dbserver
[:01000026] LAUNCH snlua dbserver
[:01000027] LAUNCH snlua id_service
[:01000009] KILL self
[:01000002] KILL self
[:0100000e] connect from 192.168.100.211:53337 (fd = 11)
Cat:logind.lua[22] user, password       1       password        DevelopServer
[:01000025] Table 'UnityMMOAccount.Account' doesn't exist
1@DevelopServer is login, secret is 447e22468b387c3d
Cat:msgagent.lua[50] user_info.agent    16777239
[:01000017] 1 is login
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist
[:01000026] Table 'UnityMMOGame.RoleList' doesn't exist

请问数据库的表是需要自己手动添加吗

**Comment by liuhaopen** [comment]
是的，详见 SkynetMMO 工程里 readme 的第三点：https://github.com/liuhaopen/SkynetMMO
