### ISSUE TITLE
大佬，这纹理是咋回事。能指点一下么[抠鼻]

### ISSUE THREAD

**Issue by Lixiaolonghh** [liuhaopen/UnityMMO#30]
![UPAFD 71E Y2%CXDB 1E)B
![UPAFD 71E Y2%CXDB 1E)BH](https://user-images.githubusercontent.com/49969479/109412165-5a07df80-79e1-11eb-9864-1ad915f9d049.png)
H](https://user-images.githubusercontent.com/49969479/109412087-f5e51b80-79e0-11eb-80c2-6b2cfcae1ebc.png)

**Comment by liuhaopen** [comment]
哈哈，因为是用到之前公司的资源，所以有版权问题，故意改成这样的，Wiki里有写的哈
