### ISSUE TITLE
看服务器是登陆成功了，但卡主不动了

### ISSUE THREAD

**Issue by wallerm** [liuhaopen/UnityMMO#32]
![image](https://user-images.githubusercontent.com/8043374/116554572-ed03be00-a92d-11eb-89f2-345f3c5c8dc7.png)

![image](https://user-images.githubusercontent.com/8043374/116554132-69e26800-a92d-11eb-9e41-abc27c740c80.png)
大佬，我刚开始unity的是使用，学的有点慢，折腾了一下午，看别人的问题解决了一下，服务器终于跑起来了，但是当我运行起来点登陆的时候，就出现了图里的情况，登陆成功了，然后不动了，就这样卡着，再点登陆就断开了，求大佬解惑~~

**Comment by liuhaopen** [comment]
刚连上 game server 后还需要握手校验，你可以在 LoginController.lua 的 Connect 函数里加下打印调试下
