### ISSUE TITLE
server端lua require是否有很多大小写问题

### ISSUE THREAD

**Issue by EricDDK** [liuhaopen/UnityMMO#4]
我改了好几个了，还是一直报错，全是大小写问题。
是否是skynet或者您的Linux终端有忽略大小写的设置呢？

**Comment by liuhaopen** [comment]
lua本来就大小写敏感的，有哪些大小写有问题？我这边没发现过

**Comment by EricDDK** [comment]
> lua本来就大小写敏感的，有哪些大小写有问题？我这边没发现过

RequireAllLuaFileInFolder("./game/scene/System")
self.scene_cfg = require("Config.scene.config_scene_"..scene_id)

**Comment by liuhaopen** [comment]
我知道了，确实是有这个问题，是因为项目我都放在windows系统上（文件名大小写不敏感的），然后在虚拟机共享跑的服务器。你是直接把Server文件夹复制到linux去了是吧？

**Comment by EricDDK** [comment]
> 我知道了，确实是有这个问题，是因为项目我都放在windows系统上（文件名大小写不敏感的），然后在虚拟机共享跑的服务器。你是直接把Server文件夹复制到linux去了是吧？

对的...我是linux的服务器。

**Comment by liuhaopen** [comment]
我看了一下，就几个地方而已，你先改下就跑得起来了，我等下再改下，或者你有空的话提下pull req
