### ISSUE TITLE
skynet跑起来后，登陆界面是什么意思？

### ISSUE THREAD

**Issue by EricDDK** [liuhaopen/UnityMMO#5]
![image](https://user-images.githubusercontent.com/33505774/58778874-bff5e600-8606-11e9-8476-541db6652055.png)
这样是算成功了嘛？
![image](https://user-images.githubusercontent.com/33505774/58778902-d308b600-8606-11e9-8b50-3f3817b33840.png)
这里我点哪个？如何配置可以登陆？需要手动在数据库插入数据嘛？
有单机模式嘛？感谢您的回复！

**Comment by liuhaopen** [comment]
UnityMMO\Server\data里有两个sql文件，导出你的mysql.
然后在登录界面的ip输入你server端的ip，如果是虚拟机的话，桥接模式就用虚拟机的ip，nat的话就要做下端口转发，反正要在主机上ping得通服务器，然后就可以登录进入游戏了。

**Comment by EricDDK** [comment]
> UnityMMO\Server\data里有两个sql文件，导出你的mysql.
> 然后在登录界面的ip输入你server端的ip，如果是虚拟机的话，桥接模式就用虚拟机的ip，nat的话就要做下端口转发，反正要在主机上ping得通服务器，然后就可以登录进入游戏了。

我对skynet不是很熟悉，我是搭建在阿里云上的，mysql也导入了，我看到您的注释里写着login server和game server不能放一台嘛？我现在ping的通但是连不上。

**Comment by liuhaopen** [comment]
login server和game server可以放一台的，ping得通连不上的话就要看看双端打印了，你按登录后没弹什么提示吗？

**Comment by EricDDK** [comment]
> login server和game server可以放一台的，ping得通连不上的话就要看看双端打印了，你按登录后没弹什么提示吗？

![image](https://user-images.githubusercontent.com/33505774/58781518-b07a9b00-860e-11e9-8363-122080f8a9bd.png)

**Comment by EricDDK** [comment]
> login server和game server可以放一台的，ping得通连不上的话就要看看双端打印了，你按登录后没弹什么提示吗？

Table 'UnityMMOGame.RoleLooksInfo' doesn't exist

![image](https://user-images.githubusercontent.com/33505774/58782169-685c7800-8610-11e9-9fef-53be56738773.png)

**Comment by liuhaopen** [comment]
sql文件确实是旧的，我昨晚才提交了新版本在dev分支里，现在合到master里了，你pull下

**Comment by liuhaopen** [comment]
ping得通但连不上的话，就去阿里云后台看端口有没有给权限，目前帐号服务用的是8001，游戏服务是8888端口。

**Comment by EricDDK** [comment]
> ping得通但连不上的话，就去阿里云后台看端口有没有给权限，目前帐号服务用的是8001，游戏服务是8888端口。

好的我连上了，等会儿提交个PR
