### ISSUE TITLE
About Navmesh.

### ISSUE THREAD

**Issue by juliolitwin** [liuhaopen/UnityMMO#8]
Yo,

A question, does the server check the navmesh? Because I did not find the navmesh reading on the server, just the client.

Congratulations on the excellent work!

**Comment by liuhaopen** [comment]
Thank you for your reminding, the server does not currently check the navmesh, 
I have added another project for this : [Navigator](https://github.com/liuhaopen/Navigator "Navigator"), that export the data via the UnityEngine.AI.NavMesh.CalculateTriangulation API,then convert to a dtNavMesh structure that can be used directly by recastnavigation.
but also need to take some time to test big scene and export the API to lua to use in skynet,
which I will handle after completing the bag and equipment system.
