### ISSUE TITLE
关于单独把Server上传到服务器后所缺失的脚本的问题

### ISSUE THREAD

**Issue by cloudhu** [liuhaopen/UnityMMO#9]
首先感谢大佬的无私分享，我从中学习到了很多知识。
如果把Server和Lua合在一起是Ok的，可是如果单独把Server上传到服务器编译后，就发现少了很多脚本，例如Lua/Common/Util下的几个脚本，可见Server依赖Lua文件夹。
当然，服务器和客户端共用一些脚本是合理的，我提出来的意思就是标注一下依赖关系。
再次感谢大佬！

**Comment by liuhaopen** [comment]
哈，感谢提醒，这个前后端共用的目录结构是要整理一下的，不过现在在重新弄新的战斗逻辑，估计要几天时间，等弄好了再整理，到时再通知下你哈

**Comment by cloudhu** [comment]
哈哈，您客气了，一点小问题，我总结了，Server依赖的就是Lua/Common/Util和Lua/Proto两个文件夹，还有就是Server\game\scene\time.lua 需要改名成Time.lua，我这里好像是区分大小写的，报个这个错，改名就解决了。

**Comment by cloudhu** [comment]
服务器Server依赖客户端Lua列表
Lua/Config
Lua/Common/Util
Lua/Proto
大佬，我有一个困惑就是，服务器端的2013端口总是被占用，每次启动就需要杀死占用的进程，才可以顺利启动，否则就会报监听错误。这算是一个bug吗？我觉得是一种困扰！

**Comment by liuhaopen** [comment]
确实是有监听2013端口的，应该是没有正常关闭后端导致的吧，你平时是怎么运行的？我大都是在虚拟机上 cd 到 Server 目录然后  ./run.sh 的，然后直接 ctrl + c 关闭掉后端，不会遇到还占用端口的情况。

**Comment by cloudhu** [comment]
按照这样的方式操作就好了，应该是我之前直接关闭窗口导致的。

**Comment by cloudhu** [comment]
对了，感谢大佬的分享，我也到CSDN上写学习笔记了，https://blog.csdn.net/qq_30137245/article/details/99305502

**Comment by liuhaopen** [comment]
写得不错，很详细。
Third Person Controller - Basic Locomotion FREE 插件可以不用的，只是我用来测试场景的，就是布好一个场景后要有个人在场景里跑来跑去看看效果。
正式游戏里主要由 MovementUpdateSystem 控制角色的行走逻辑

**Comment by cloudhu** [comment]
噢，我还没有学习到那里，还在恶补ECS
